<?php
declare(strict_types=1);

namespace App\Service;

use Cake\Core\Configure;
use Intervention\Image\Drivers\Gd\Driver as GdDriver;
use Intervention\Image\ImageManager;

/**
 * Image processing service.
 *
 * Uses intervention/image v4 with GD driver (no Imagick required).
 * HEIC files are not supported by GD — they are rejected with a clear message.
 *
 * Supported inputs: image/jpeg, image/png, image/webp, image/gif
 */
class ImageService
{
    private const THUMB_QUALITY = 82;

    /**
     * Validate an uploaded file's MIME type and size.
     *
     * @return array{ok:bool, error:string|null}
     */
    public static function validate(string $tmpPath, string $clientMime): array
    {
        $maxMb = (int)Configure::read('Photowall.max_upload_mb');

        // Real MIME check (don't trust client header alone).
        $realMime = mime_content_type($tmpPath) ?: $clientMime;

        if (in_array($realMime, ['image/heic', 'image/heif'], true)) {
            return [
                'ok'    => false,
                'error' => 'Las fotos HEIC de iPhone no son soportadas. En Ajustes > Camara > Formatos, elige "Mas compatible" para subir en JPEG.',
            ];
        }

        $acceptedMime = ['image/jpeg', 'image/png', 'image/webp', 'image/gif'];
        if (!in_array($realMime, $acceptedMime, true)) {
            return ['ok' => false, 'error' => "Tipo de archivo no soportado ({$realMime}). Sube una foto JPEG, PNG o WEBP."];
        }

        $sizeMb = filesize($tmpPath) / 1024 / 1024;
        if ($sizeMb > $maxMb) {
            return ['ok' => false, 'error' => "La foto es demasiado grande (max {$maxMb} MB)."];
        }

        return ['ok' => true, 'error' => null];
    }

    /**
     * Generate a thumbnail and save it to $destPath.
     *
     * - Long edge capped at configured px.
     * - EXIF auto-orient applied.
     * - Output is always JPEG for consistent delivery.
     *
     * @throws \RuntimeException on failure
     */
    public static function generateThumb(string $sourcePath, string $destPath, ?int $maxEdge = null): void
    {
        $maxEdge = $maxEdge ?? ((int)Configure::read('Photowall.thumb_max_edge_px') ?: 1080);

        $manager = ImageManager::usingDriver(new GdDriver());
        $image = $manager->decodePath($sourcePath);

        // Auto-orient using EXIF data (fixes rotated iPhone JPEGs).
        $image->orient();

        // Scale down if larger than max edge — never upscale.
        $image->scaleDown($maxEdge, $maxEdge);

        // Ensure destination directory exists.
        $dir = dirname($destPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0775, true);
        }

        $image->save($destPath, quality: self::THUMB_QUALITY);
    }

    /**
     * Composite a PNG frame (with transparent center) onto a JPEG photo.
     *
     * The output canvas takes the FRAME's aspect ratio, so the frame is never
     * stretched or distorted — its corners and borders stay perfectly aligned.
     * The photo is "cover"-fitted into that canvas (fills it completely, any
     * overflow cropped, centered). Transparent areas of the frame reveal the
     * photo beneath via alpha blending.
     *
     * Modifies $imagePath in-place (overwrites the file as JPEG).
     *
     * @throws \RuntimeException on failure
     */
    public static function applyFrame(string $imagePath, string $framePath): void
    {
        // Load photo (always JPEG at this point — generated by generateThumb).
        $photo = @imagecreatefromjpeg($imagePath);
        if (!$photo) {
            throw new \RuntimeException("applyFrame: cannot load photo $imagePath");
        }
        $pw = imagesx($photo);
        $ph = imagesy($photo);

        // Load frame PNG (must preserve alpha).
        $frameSrc = @imagecreatefrompng($framePath);
        if (!$frameSrc) {
            imagedestroy($photo);
            throw new \RuntimeException("applyFrame: cannot load frame $framePath");
        }
        $fw = imagesx($frameSrc);
        $fh = imagesy($frameSrc);

        // Output canvas = frame's aspect ratio, sized to the photo's long edge.
        $frameAspect = $fw / $fh;
        $longEdge = max($pw, $ph);
        if ($frameAspect >= 1.0) {
            $cw = $longEdge;
            $ch = (int)max(1, round($longEdge / $frameAspect));
        } else {
            $ch = $longEdge;
            $cw = (int)max(1, round($longEdge * $frameAspect));
        }

        $canvas = imagecreatetruecolor($cw, $ch);
        imagealphablending($canvas, true);
        // Base fill — only visible if the photo somehow fails to cover (it won't).
        $bg = imagecolorallocate($canvas, 0, 0, 0);
        imagefilledrectangle($canvas, 0, 0, $cw - 1, $ch - 1, $bg);

        // Cover-fit the photo: fill the whole canvas, crop overflow, centered.
        $canvasAspect = $cw / $ch;
        $photoAspect = $pw / $ph;
        if ($photoAspect > $canvasAspect) {
            // Photo relatively wider → match canvas height, overflow on width.
            $dh = $ch;
            $dw = (int)round($ch * $photoAspect);
        } else {
            // Photo relatively taller → match canvas width, overflow on height.
            $dw = $cw;
            $dh = (int)round($cw / $photoAspect);
        }
        $dx = (int)round(($cw - $dw) / 2);
        $dy = (int)round(($ch - $dh) / 2);
        imagecopyresampled($canvas, $photo, $dx, $dy, 0, 0, $dw, $dh, $pw, $ph);
        imagedestroy($photo);

        // Composite the frame on top. Frame aspect == canvas aspect → no distortion.
        // alphablending is on, so transparent frame pixels reveal the photo.
        imagecopyresampled($canvas, $frameSrc, 0, 0, 0, 0, $cw, $ch, $fw, $fh);
        imagedestroy($frameSrc);

        imagejpeg($canvas, $imagePath, self::THUMB_QUALITY);
        imagedestroy($canvas);
    }

    /**
     * Save original file to $destPath.
     * Converts PNG/WEBP to JPEG for storage consistency.
     * JPEG originals are copied as-is to preserve quality.
     */
    public static function saveOriginal(string $tmpPath, string $destPath): void
    {
        $dir = dirname($destPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0775, true);
        }

        $mime = mime_content_type($tmpPath) ?: '';

        if (in_array($mime, ['image/png', 'image/webp', 'image/gif'], true)) {
            $manager = ImageManager::usingDriver(new GdDriver());
            $image = $manager->decodePath($tmpPath);
            $image->orient();
            $image->save($destPath, quality: 90);
        } else {
            // JPEG — copy as-is to preserve quality.
            copy($tmpPath, $destPath);
        }
    }
}
